### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by pricelessbrewing** [joeberthelot88/CSS-Grid-Boilerplate#1]
Would be nice to see some examples right away

**Comment by pixelscript-io** [comment]
Could you please explain?  The example.html file contains several examples.

**Comment by pricelessbrewing** [comment]
Apologies, apparently I didn't save my edit. Was trying to suggest putting the examples on the demo page, or as links to a codepen (or similar).

**Comment by pixelscript-io** [comment]
A link is now added to the Readme.md file and is located in docs/index.html.
